import{a as l,S as f,i as u}from"./assets/vendor-f86ecf37.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))p(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&p(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function p(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const m="live_PhwyQ190iBWMD41jyFSre7c2tEjoQPL9JZN3xA9orTnwo4Tysj2GLchEe0O80FAe";l.defaults.headers.common["x-api-key"]=m;async function y(){try{return(await l.get("https://api.thecatapi.com/v1/breeds")).data}catch{throw new Error("Failed to fetch cat breeds")}}async function h(t){try{return(await l.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${t}`)).data}catch{throw new Error("Failed to fetch cat by breed")}}const d=document.querySelector(".breed-select"),i=document.querySelector(".cat-info"),g=document.querySelector(".loader"),b=document.querySelector(".error"),w=new f({select:d,settings:{placeholderText:"Choose a breed"}}),v={text:"",value:"",placeholder:!0};function n(t){g.style.display=t?"block":"none"}function a(t){b.style.display=t?"block":"none"}async function S(){try{n(!0),a(!1),await y().then(t=>{const o=t.map(s=>({text:s.name,value:s.id}));w.setData([v,...o])}),n(!1),d.addEventListener("change",L)}catch{a(!0),n(!1),u.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"center"})}}async function L(){try{n(!0),a(!1);const t=d.value,o=await h(t);n(!1);const s=o[0];i.innerHTML=`
        <div class="cat-container">
            <img class="cat-img" src="${s.url}" alt="сat">
        <div class="cat-text">
            <p class="cat-name" img">${s.breeds[0].name}</p>
            <p class="cat-description">${s.breeds[0].description}</p>
            <p class="cat-temperament"><p>Temperament:</p> ${s.breeds[0].temperament}</p>
        </div> </div>`,i.style.display="block"}catch{a(!0),n(!1),i.style.display="none",u.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"center"})}}S();
//# sourceMappingURL=commonHelpers.js.map
